BaseUri http://49.249.28.218:8081/AppServer/Online_Shopping_Application
DBUrl jdbc:mysql://49.249.28.218:3333/mart_vibe
DB_UserName root
DB_Password root
ClientId ninza-client
client_secret gPQBf1Yxew5OMccMhzos1GefIyiSnXzM